### ISSUE TITLE
User has NO indication if tap of the "Save Location to Tour" button has been tapped.  [BUG]

### ISSUE THREAD

**Issue by combobulated** [cforlando/orlando-walking-tours-ios#33]
Results in multiple entries of tour locations.
This button is in the detail view of 'Add locations' tableview.

**Comment by WERUreo** [comment]
The multiple entries of tour locations was fixed in pull request #32.  Tapping "Save Location to Tour" still gives no indication that something happened. 

I feel like tapping the button should take the user back to the previous screen and perhaps even remove it from the list of locations to choose from and/or disable/hide the button.

**Comment by WERUreo** [comment]
Because we are essentially restarting the project, any bugs found in the old baseline are now irrelevant.
